name: Update by language
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  update-by-language:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install starred
      - name: Get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_ENV"
      - name: Update category by language
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          starred \
          --username "${USERNAME}" \
          --repository "${REPOSITORY}" \
          --token "${GITHUB_TOKEN}" \
          --sort \
          --message "docs(language): bump data" \
          --filename by-language.md
